id: P010373
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG10294
  title: རྒྱ་བོད་མཁས་གྲུབ་རིམ་བྱོན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    52f6db12010d483a848ba690c4cc5a20:
      image_group_id: I1KG10644
      title: ''
      volume_number: 1
      total_pages: 1066
      base_file: v001.txt
    99bc8f8063f043a4a048c5629035ca88:
      image_group_id: I1KG10645
      title: ''
      volume_number: 2
      total_pages: 430
      base_file: v002.txt
    72fd4a66a0854643954a7f3fd01dfb16:
      image_group_id: I1KG10646
      title: ''
      volume_number: 3
      total_pages: 906
      base_file: v003.txt
    d50cc142d994407fa654b2f3c47b2b19:
      image_group_id: I1KG10647
      title: ''
      volume_number: 4
      total_pages: 798
      base_file: v004.txt
    66d107cc0eb745fdb798cb548dee9deb:
      image_group_id: I1KG10648
      title: ''
      volume_number: 5
      total_pages: 1011
      base_file: v005.txt
    b26db9cd8274431cbfbf0f22db57fb10:
      image_group_id: I1KG10649
      title: ''
      volume_number: 6
      total_pages: 650
      base_file: v006.txt
    b3a2c4ba754b4a33b603e2bdc9a895ba:
      image_group_id: I1KG10650
      title: ''
      volume_number: 7
      total_pages: 688
      base_file: v007.txt
    c863f00a66794019ab769c92a8b833b2:
      image_group_id: I1KG10651
      title: ''
      volume_number: 8
      total_pages: 676
      base_file: v008.txt
    fcc4a1ff6cf1458188a75c3ea7fd5317:
      image_group_id: I1KG10652
      title: ''
      volume_number: 9
      total_pages: 705
      base_file: v009.txt
    f624a39423ea4789a8a2083f0705b4a5:
      image_group_id: I1KG10653
      title: ''
      volume_number: 10
      total_pages: 600
      base_file: v010.txt
    27bcb229ca364b4eaad3fabd94fd43bf:
      image_group_id: I1KG10654
      title: ''
      volume_number: 11
      total_pages: 648
      base_file: v011.txt
    d7cc3d56864044d593740350a1c5a1bf:
      image_group_id: I1KG10655
      title: ''
      volume_number: 12
      total_pages: 470
      base_file: v012.txt
