id: IABC700EA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:42:05+00:00'
last_modified: '2022-06-08T13:07:23.033203+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10294
  title: རྒྱ་བོད་མཁས་གྲུབ་རིམ་བྱོན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F8E9:
      image_group_id: I1KG10644
      title: ''
      total_pages: 1066
      order: 1
      base_file: F8E9.txt
    '6117':
      image_group_id: I1KG10645
      title: ''
      total_pages: 430
      order: 2
      base_file: 6117.txt
    AAEA:
      image_group_id: I1KG10646
      title: ''
      total_pages: 906
      order: 3
      base_file: AAEA.txt
    3A3C:
      image_group_id: I1KG10647
      title: ''
      total_pages: 798
      order: 4
      base_file: 3A3C.txt
    '3740':
      image_group_id: I1KG10648
      title: ''
      total_pages: 1011
      order: 5
      base_file: 3740.txt
    CA8F:
      image_group_id: I1KG10649
      title: ''
      total_pages: 650
      order: 6
      base_file: CA8F.txt
    '5313':
      image_group_id: I1KG10650
      title: ''
      total_pages: 688
      order: 7
      base_file: 5313.txt
    C8CB:
      image_group_id: I1KG10651
      title: ''
      total_pages: 676
      order: 8
      base_file: C8CB.txt
    '5061':
      image_group_id: I1KG10652
      title: ''
      total_pages: 705
      order: 9
      base_file: 5061.txt
    5AC0:
      image_group_id: I1KG10653
      title: ''
      total_pages: 600
      order: 10
      base_file: 5AC0.txt
    35A6:
      image_group_id: I1KG10654
      title: ''
      total_pages: 648
      order: 11
      base_file: 35A6.txt
    C3AF:
      image_group_id: I1KG10655
      title: ''
      total_pages: 470
      order: 12
      base_file: C3AF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
